import Navbar from "@/components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <div className="px-20">
          <Navbar />
          <main className="pt-20">{children}</main>
        </div>
      </body>
    </html>
  );
}
